server:
  port: 9090

aws:
  region: us-east-1
  dynamodb:
      table-name: ${AWS_DYNAMODB_TABLE_NAME}

capture:
  bucket-name: ${CAPTURE_BUCKET_NAME}

logging:
  level:
    org.springframework.web: DEBUG

replay:
  baseline-policy-service-url: ${REPLAY_BASELINE_POLICY_SERVICE_URL}
  candidate-policy-service-url: ${REPLAY_CANDIDATE_POLICY_SERVICE_URL}
  thread-pool-size: 10